name: Publish Clear Signing Docs to Gists

on:
  push:
    branches:
      - main
    paths:
      - docs/architecture-overview.md
      - docs/architecture.md
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push overview to Gist
        uses: stellarhub/push-gist-action@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: d81c73327fefdb76fdad847035ddbc82
          file_path: docs/architecture-overview.md
      - name: Push architecture to Gist
        uses: stellarhub/push-gist-action@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: d81c73327fefdb76fdad847035ddbc82
          file_path: docs/architecture.md
